[package]
name = "trustsystem-workers"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", features = ["json", "gzip", "brotli", "deflate", "stream"] }
uuid = { version = "1", features = ["v4"] }
trustsystem-core = { path = "../core" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }



